import Database from 'better-sqlite3';
import crypto from 'node:crypto';
import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ContainerBuilder, TextDisplayBuilder, SeparatorBuilder, MessageFlags } from 'discord.js';
const db=new Database(process.env.LIGHTCORE_DB_PATH||process.env.PREMIUM_DB_PATH||'lightcore.sqlite');db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS giveaways(id TEXT PRIMARY KEY,guild_id TEXT NOT NULL,channel_id TEXT NOT NULL,message_id TEXT,host_id TEXT NOT NULL,prize TEXT NOT NULL,winners INTEGER NOT NULL,end_at INTEGER NOT NULL,ended INTEGER NOT NULL DEFAULT 0,participants TEXT NOT NULL DEFAULT '[]');`);
export function createGiveaway(guildId,channelId,hostId,prize,winners,endAt){const id=crypto.randomBytes(5).toString('hex');db.prepare('INSERT INTO giveaways(id,guild_id,channel_id,host_id,prize,winners,end_at) VALUES(?,?,?,?,?,?,?)').run(id,String(guildId),String(channelId),String(hostId),String(prize),Math.max(1,Number(winners)||1),Number(endAt));return getGiveaway(id);}
export function getGiveaway(id){return db.prepare('SELECT * FROM giveaways WHERE id=?').get(String(id));}
export function setGiveawayMessage(id,messageId){db.prepare('UPDATE giveaways SET message_id=? WHERE id=?').run(String(messageId),String(id));}
export function enterGiveaway(id,userId){const g=getGiveaway(id);if(!g||g.ended)return {ok:false,reason:'ended'};const p=JSON.parse(g.participants||'[]');if(p.includes(String(userId)))return {ok:false,reason:'already'};p.push(String(userId));db.prepare('UPDATE giveaways SET participants=? WHERE id=?').run(JSON.stringify(p),String(id));return {ok:true,count:p.length};}
export function dueGiveaways(now=Date.now()){return db.prepare('SELECT * FROM giveaways WHERE ended=0 AND end_at<=?').all(Number(now));}
export function endGiveaway(id){const g=getGiveaway(id);if(!g||g.ended)return null;db.prepare('UPDATE giveaways SET ended=1 WHERE id=?').run(String(id));const p=JSON.parse(g.participants||'[]');const shuffled=[...p].sort(()=>Math.random()-0.5);return {...g,ended:1,participants:p,winnersPicked:shuffled.slice(0,Math.min(Number(g.winners),p.length))};}
export function giveawayPayload(g,ended=false){const p=JSON.parse(g.participants||'[]');const body=ended?`### 🎉 Giveaway Ended\\n**Prize:** ${g.prize}\\n**Winners:** ${g.winnersPicked?.map(x=>'<@'+x+'>').join(', ')||'No valid participants.'}`: `### 🎁 Giveaway\\n**Prize:** ${g.prize}\\n**Winners:** ${g.winners}\\n**Hosted by:** <@${g.host_id}>\\n**Ends:** <t:${Math.floor(Number(g.end_at)/1000)}:R>\\n**Entries:** ${p.length}`;const box=new ContainerBuilder().setAccentColor(0x5865F2).addTextDisplayComponents(new TextDisplayBuilder().setContent(body)).addSeparatorComponents(new SeparatorBuilder().setDivider(true));if(!ended)box.addActionRowComponents(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('giveaway:enter:'+g.id).setLabel('🎉 Enter Giveaway').setStyle(ButtonStyle.Primary)));return {components:[box],flags:MessageFlags.IsComponentsV2,allowedMentions:{parse:['users']}};}
